import { fib } from "./nice";
console.log(fib(30));
console.log("chuj");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");

console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
console.log("fhcusdfuhisdudsdsahifhuds");
